# netlify.toml

[build]
  # No build step—just publish our docs folder
  command = ""
  publish = "docs"

# Redirect /insights/* to the nested insights files
[[redirects]]
  from   = "/insights/*"
  to     = "/insights/:splat"
  status = 200
  force  = true

# Ensure /insights (no slash) redirects properly
[[redirects]]
  from   = "/insights"
  to     = "/insights/"
  status = 301
